// Firestore document shapes. Every collection keeps a numeric `id` field that
// is also the document ID (as a string), so API contracts stay unchanged from
// the previous MySQL schema. Timestamps are epoch milliseconds, except the user
// audit fields, which are exposed as Dates.
import type { BoardRole, ChecklistAnswerType, ChecklistAnswerValue, ConfidentialityLevel, DecisionOutcome, LifecycleStatus, Priority, SubjectType, WorkStatus } from "./domain";

export type MembershipRole = Exclude<BoardRole, "administrator" | "general_secretariat_head">;
export type AssigneeRole = Exclude<MembershipRole, "requester">;

export type User = { id: number; firebaseUid: string | null; name: string | null; email: string | null; loginMethod: string | null; role: "user" | "admin"; isGeneralSecretariatHead?: boolean; createdAt: Date; updatedAt: Date; lastSignedIn: Date };
export type Board = { id: number; code: string; nameAr: string; nameEn: string | null; mandateAr: string | null; mandateEn: string | null; isActive: boolean; allowWithdrawDuringBoardHeadReview: boolean; createdByUserId: number; createdAt: number; updatedAt: number; descriptionAr: string | null; descriptionEn: string | null };
export type Specialty = { id: number; boardId: number; code: string; nameAr: string; nameEn: string | null; isActive: boolean; createdAt: number; updatedAt: number };
export type BoardMembership = { id: number; userId: number; boardId: number; role: MembershipRole; isActive: boolean; assignedByUserId: number; createdAt: number; updatedAt: number };
export type ChecklistTemplate = { id: number; boardId: number; specialtyId: number | null; subjectType: SubjectType | null; nameAr: string; nameEn: string | null; version: number; status: "draft" | "active" | "retired"; createdByUserId: number; activatedAt: number | null; retiredAt: number | null; createdAt: number; updatedAt: number };
export type ChecklistQuestion = { id: number; checklistTemplateId: number; code: string; textAr: string; textEn: string | null; answerType: ChecklistAnswerType; required: boolean; sortOrder: number; showIfJson: ChecklistCondition | null; linkedDocumentType: string | null; optionsJson: unknown; isActive: boolean; createdAt: number; updatedAt: number };
export type SubjectRequest = { id: number; referenceNumber: string; revision: number; rowVersion: number; title: string; subjectType: SubjectType; priority: Priority; confidentialityLevel: ConfidentialityLevel; source: string; requesterUserId: number; requesterOrganization: string | null; requesterContactDetails: string | null; preferredCommunicationChannel: string | null; boardId: number; specialtyId: number; assignedSecretaryMemberId: number | null; currentAssigneeId: number | null; consultedByUserId?: number | null; dueDate: number | null; description: string | null; background: string | null; objective: string | null; requestedOutcome: string | null; justification: string | null; urgencyExplanation: string | null; secretaryFindings: string | null; summary: string | null; recommendations: string | null; internalNotes: string | null; completenessResult: boolean | null; jurisdictionResult: boolean | null; duplicationResult: boolean | null; boardHeadOutcome: string | null; decisionReasonCode: string | null; decisionNote: string | null; decisionNoteRequesterVisible: boolean | null; decisionAt: number | null; decisionByUserId: number | null; lifecycleStatus: LifecycleStatus; workStatus: WorkStatus; agendaHandoffStatus: string | null; checklistTemplateId: number | null; checklistTemplateVersion: number | null; correlationId: string | null; agendaItemId: string | null; createdAt: number; updatedAt: number; submittedAt: number | null; closedAt: number | null };
export type ChecklistAnswer = { id: number; subjectRequestId: number; checklistQuestionId: number; answerValue: ChecklistAnswerValue; comment: string | null; evidenceAttachmentId: number | null; responderUserId: number | null; responseDate: number; finalConfirmation: boolean; updatedAt: number };
export type ChecklistAnswerEdit = { id: number; checklistAnswerId: number; previousValue: unknown; newValue: unknown; editedByUserId: number; editedAt: number };
export type RequestAssignment = { id: number; subjectRequestId: number; assigneeUserId: number; assigneeRole: AssigneeRole; assignedByUserId: number; status: "active" | "released" | "completed"; note: string | null; assignedAt: number; releasedAt: number | null };
export type RequestDecision = { id: number; subjectRequestId: number; outcome: DecisionOutcome; reasonCode: string; note: string | null; requesterVisible: boolean; decidedByUserId: number; decidedAt: number };
export type RequestHistory = { id: number; subjectRequestId: number; actorUserId: number; actorRoleAtTime: BoardRole; action: string; beforeState: unknown; afterState: unknown; note: string | null; correlationId: string | null; createdAt: number };
export type RequestSnapshot = { id: number; subjectRequestId: number; revision: number; content: unknown; createdByUserId: number; createdAt: number };
export type RequestAttachment = { id: number; subjectRequestId: number; storageKey: string; accessUrl: string | null; originalFileName: string; documentType: string; description: string | null; mimeType: string; byteSize: number; checksumSha256: string | null; version: number; uploadedByUserId: number; requesterVisible: boolean; reviewStatus: "pending" | "accepted" | "rejected"; replacesAttachmentId: number | null; isActive: boolean; uploadedAt: number };

export type ChecklistCondition = { questionCode: string; operator: "equals" | "not_equals" | "includes"; value: unknown };
